spring:
  application:
    name: blaybus-dev

  config:
    import:
      - file:env/dev.env

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_REFRESH_KEY}