spring:
  application:
    name: blaybus-dev

  aot:
    enabled: false  # AOT 비활성화 설정 추가

  config:
    import:
      - optional:file:env/dev.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: ${OAUTH2_CLIENT_NAME}
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            authorization-grant-type: ${OAUTH2_GRANT_TYPE}
            client-authentication-method: ${OAUTH2_AUTH_METHOD}
            redirect-uri: ${OAUTH2_REDIRECT_URL}
            scope:
              - profile
              - email

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

kakao:
  pay:
    admin-key: ${PAY_SECRET_KEY}
    cid: ${PAY_CLIENT}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR

frontend:
  url: ${FRONTEND_URL}

server:
  url: ${SERVER_URL}
