package blaybus.domain.meeting.application.service.impl;

import blaybus.domain.meeting.application.service.GoogleMeetService;
import blaybus.domain.meeting.infra.feignclient.GoogleMeetClient;
import blaybus.domain.meeting.infra.feignclient.dto.request.ConferenceRequest;
import blaybus.domain.meeting.infra.feignclient.dto.response.ConferenceResponse;
import blaybus.domain.meeting.presentation.dto.request.MeetingCreateRequest;
import blaybus.domain.meeting.presentation.dto.response.MeetingResponse;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.format.DateTimeFormatter;

@Service
@RequiredArgsConstructor
public class GoogleMeetServiceImpl implements GoogleMeetService {
    private final GoogleMeetClient googleMeetClient;

    @Override
    public MeetingResponse createMeeting(MeetingCreateRequest request) {

        // 디자이너 이름을 가져와야 함... Id로 조회
        Designer designer = designerRepository.findById(request.designerId())
                .orElseThrow(() -> new EntityNotFoundException("디자이너를 찾을 수 없습니다."));

        try {
            ConferenceResponse response = googleMeetClient.createMeeting(
                    createConferenceRequest(request)
            );
            return new MeetingResponse(response.getHangoutLink());
        } catch (Exception e) {
            throw new RuntimeException("Failed to create Google Meet link", e);
        }
    }

    private ConferenceRequest createConferenceRequest(MeetingCreateRequest request) {
        ConferenceRequest conferenceRequest = new ConferenceRequest();

        // 미팅 제목 자동 생성
        String autoGeneratedTitle = String.format(
                "%s님과의 상담 - %s",
                designer.getName(),
                request.startTime().format(DateTimeFormatter.ofPattern("M월 d일 a h시 mm분"))
        );
        conferenceRequest.setSummary(autoGeneratedTitle);

        // 시작 시간 설정
        ConferenceRequest.EventDateTime start = new ConferenceRequest.EventDateTime();
        start.setDateTime(request.startTime().toString());
        conferenceRequest.setStart(start);

        return conferenceRequest;
    }
}
